version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - go
    groups:
      opentelemetry:
        patterns:
          - "go.opentelemetry.io/*"
      google-cloud:
        patterns:
          - "cloud.google.com/*"
          - "google.golang.org/*"
          - "firebase.google.com/*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker
